### ISSUE TITLE
Reduce the amount of calls to Github or prevent them once failed

### ISSUE THREAD

**Issue by annakocheshkova** [Microsoft/AppCenter-SDK-Unity-Extension#37]
**Issue:** We make too much calls to GH API and as a result, customers might get 403 Forbidden (this is due to daily limit of calls reached). 

**Resolution:** We should see if we can reduce the amount of calls and stop calling API once we received 403 (for a day).

https://github.com/microsoft/appcenter-sdk-unity/issues/381

**Comment by Jamminroot** [comment]
Hey, @mtes133 (and @annakocheshkova =) ), just wanted to let you know that this is being addressed by our team currently, no ETAs I can provide though.

**Comment by olmisa** [comment]
Should be fixed here https://github.com/microsoft/AppCenter-SDK-Unity-Extension/pull/38 . The fix is available in this release https://github.com/microsoft/AppCenter-SDK-Unity-Extension/releases/tag/2.0.0.
