### ISSUE TITLE
Source control guidance

### ISSUE THREAD

**Issue by kimbirkelund** [Microsoft/AppCenter-SDK-Unity-Extension#43]
Since adding the SDK creates a lot of files in a folder that you'd normally have in source control, some guidance on which files to commit and which will be automatically regenerated when the project loads would be nice.

**Comment by russelarms** [comment]
Hi there, 
It depends on the platform, Unity version and your current .gitignore file.
Probably you can safely put these folders to .gitignore:
```
Library/
Temp/
```

**Comment by russelarms** [comment]
Hi,
these folders and files are essential for the SDK functionality:
```
Assets/AppCenter/
Assets/PlayServicesResolver/
ProjectSettings/GvhProjectSettings.xml
```
and these folders can be moved under .gitignore:
```
Library/
Temp/
```

**Comment by kimbirkelund** [comment]
Hi

Yeah, that's my basic setup. However it appears there are some files in the AppCenter folder that gets updated automatically, so I was wondering if those could be ignored too.

**Comment by russelarms** [comment]
@kimbirkelund what specific files are we talking about?

**Comment by kimbirkelund** [comment]
The aar files. Maybe some that appeared to be iOS specific, but I'm less sure.

**Comment by russelarms** [comment]
The **aar** files that I found on a fresh Unity project are located inside `Assets/AppCenter/` and required for the SDK to work correctly.
```
Assets/AppCenter/Plugins/Android/appcenter-release.aar
Assets/AppCenter/Plugins/Android/appcenter-analytics-release.aar
Assets/AppCenter/Plugins/Android/appcenter-crashes-release.aar
...
```
iOS analog is `Assets/AppCenter/Plugins/iOS/Analytics/AppCenter***.framework`
But they are also located under `Assets/AppCenter`.

Where the files that you are talking about are located?

**Comment by kimbirkelund** [comment]
Those are the files I'm talking about. But it may be that I'm mistaken in thinken they are updated other than when the SDK is updated.

**Comment by russelarms** [comment]
As far as I know, these files are only updated with the SDK.

**Comment by kimbirkelund** [comment]
Fair enough. I'll close and reopen if the issue resurfaces.
