### ISSUE TITLE
AppCenterEditorHelper.uiStyle is null on 2019.2

### ISSUE THREAD

**Issue by GenGames** [Microsoft/AppCenter-SDK-Unity-Extension#51]
I just added the SDK into my project, when I open the Window>App center, the editor tab is blank and a handful of errors show up in the console, pasted below for reference. Looks like the uiStyle set up in the AppCenterEditorHeloper is being read as null, I've tried plugging a couple of leaks or doing a handful of small quick workarounds, but have quickly found that uiStyle isn't something that can be easily bypassed. I may have perhaps have messed up when implementing the sdk? when I downloaded and unzipped the package, I did so in a plugins folder of my project's root folder (though the plugins folder is still within the project of course)? I didn't see any notes anywhere saying that anything but the AppCenterEditorExtensions Folder should be in the root. 

I'm using Unity 2019.2.4 and downloaded the current version of the App Center SDK (3.0).

## uiStyle == null error
NullReferenceException: Object reference not set to an instance of an object
AppCenterEditor.AppCenterEditorMenu.DrawMenu () (at Assets/ARPlugins/AppCenter-SDK-Unity-Extension-develop/Source/Assets/AppCenterEditorExtensions/Editor/Scripts/Panels/AppCenterEditorMenu.cs:22)

## unknown error
GUI Error: You are pushing more GUIClips than you are popping. Make sure they are balanced.
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

Let me know if there's anything else that would be helpful for troubleshooting. Thanks all

**Comment by Jamminroot** [comment]
Hey, @GenGames, thanks for reaching out.

We've tested Unity SDK on a sample project with unity version 2019.2.4f1 - and could not reproduce the problem. Can you check if the problem is reproduced for you on a clean project?

**Comment by GenGames** [comment]
Thanks for the response,

Upon reimporting the unity package file, we realized that this was an issue with some of our content using similar naming conventions, upon resolving that discrepancy and reimporting the package + restarting the editor the problem was resolved. Sorry for the trouble!

**Comment by Jamminroot** [comment]
Glad to hear it's resolved!
