### ISSUE TITLE
Unable to add package through Unity Package Manager

### ISSUE THREAD

**Issue by YoyoMario** [Microsoft/AppCenter-SDK-Unity-Extension#53]
Hey, 
it's not possible to install this package through UPM. Here's the link for errors that were thrown -> https://prnt.sc/19z4nqb

Kind regards,
Mario

**Comment by DmitriyKirakosyan** [comment]
Hi @YoyoMario 

Thank you for bringing this issue to our attention!
We will check it and get back to you asap.

Sorry for late reply.

**Comment by AnatolyPristensky** [comment]
Hello @YoyoMario,
AppCenter-SDK-Unity-Extension it's not a package but extension, so expectedly it can't be added via UPM.
You should use the following steps to install AppCenter-SDK-Unity-Extension into your project:

1. Download [this Asset Package](https://github.com/Microsoft/AppCenter-SDK-Unity-Extension/releases) and import `.unitypackage` file into a new or existing project;
2. Open the Editor Extensions via the Unity menu: Window > App Center > Editor Extensions;
3. Editor Extensions will automatically detect if you have a App Center SDK installed.

**Comment by DmitriyKirakosyan** [comment]
I'm closing this issue, but feel free to reopen if the problem remains or you have additional questions.
