### ISSUE TITLE
Slow domain reload.

### ISSUE THREAD

**Issue by astro75** [Microsoft/AppCenter-SDK-Unity-Extension#62]
This plugin adds 600ms to domain reload time.

To measure:
- Go to Preferences > Diagnostics > Core
- Enable `EnableDomainReloadTimings`
- Recompile the code trigger domain reload.
- Check editor log file

```
InitializeOnLoad Startup: 606ms
	ProcessInitializeOnLoadAttribute(AppCenterEditor.AppCenterEditor+Startup, Assembly-CSharp-Editor, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null): 606ms
		Assembly-CSharp-Editor.dll!::Startup..cctor(): 606ms
			GC.Alloc(48): 7ms in 75338 occurrences
			GC.Alloc(64): 1ms in 6918 occurrences
```

**Comment by IlyaBausovAkvelon** [comment]
Hi @astro75!
Thank you for reporting this issue. We need some time to investigate it.

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to add support for this feature in the next year, I'm closing the issue.
